package actions

import (

  "fmt"
  "net/http"
  "github.com/gobuffalo/buffalo"
  "github.com/gobuffalo/pop/v5"
  "github.com/gobuffalo/x/responder"
  "jukedec_api/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Album)
// DB Table: Plural (albums)
// Resource: Plural (Albums)
// Path: Plural (/albums)
// View Template Folder: Plural (/templates/albums/)

// AlbumsResource is the resource for the Album model
type AlbumsResource struct{
  buffalo.Resource
}

// List gets all Albums. This function is mapped to the path
// GET /albums
func (v AlbumsResource) List(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  albums := &models.Albums{}

  // Paginate results. Params "page" and "per_page" control pagination.
  // Default values are "page=1" and "per_page=20".
  q := tx.PaginateFromParams(c.Params())

  // Retrieve all Albums from the DB
  if err := q.All(albums); err != nil {
    return err
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // Add the paginator to the context so it can be used in the template.
    c.Set("pagination", q.Paginator)

    c.Set("albums", albums)
    return c.Render(http.StatusOK, r.HTML("/albums/index.plush.html"))
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(200, r.JSON(albums))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(200, r.XML(albums))
  }).Respond(c)
}

// Show gets the data for one Album. This function is mapped to
// the path GET /albums/{album_id}
func (v AlbumsResource) Show(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Album
  album := &models.Album{}

  // To find the Album the parameter album_id is used.
  if err := tx.Find(album, c.Param("album_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    c.Set("album", album)

    return c.Render(http.StatusOK, r.HTML("/albums/show.plush.html"))
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(200, r.JSON(album))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(200, r.XML(album))
  }).Respond(c)
}

// New renders the form for creating a new Album.
// This function is mapped to the path GET /albums/new
func (v AlbumsResource) New(c buffalo.Context) error {
  c.Set("album", &models.Album{})

  return c.Render(http.StatusOK, r.HTML("/albums/new.plush.html"))
}
// Create adds a Album to the DB. This function is mapped to the
// path POST /albums
func (v AlbumsResource) Create(c buffalo.Context) error {
  // Allocate an empty Album
  album := &models.Album{}

  // Bind album to the html form elements
  if err := c.Bind(album); err != nil {
    return err
  }

  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Validate the data from the html form
  verrs, err := tx.ValidateAndCreate(album)
  if err != nil {
    return err
  }

  if verrs.HasAny() {
    return responder.Wants("html", func (c buffalo.Context) error {
      // Make the errors available inside the html template
      c.Set("errors", verrs)

      // Render again the new.html template that the user can
      // correct the input.
      c.Set("album", album)

      return c.Render(http.StatusUnprocessableEntity, r.HTML("/albums/new.plush.html"))
    }).Wants("json", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
    }).Wants("xml", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
    }).Respond(c)
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // If there are no errors set a success message
    c.Flash().Add("success", T.Translate(c, "album.created.success"))

    // and redirect to the show page
    return c.Redirect(http.StatusSeeOther, "/albums/%v", album.ID)
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(http.StatusCreated, r.JSON(album))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(http.StatusCreated, r.XML(album))
  }).Respond(c)
}

// Edit renders a edit form for a Album. This function is
// mapped to the path GET /albums/{album_id}/edit
func (v AlbumsResource) Edit(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Album
  album := &models.Album{}

  if err := tx.Find(album, c.Param("album_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  c.Set("album", album)
  return c.Render(http.StatusOK, r.HTML("/albums/edit.plush.html"))
}
// Update changes a Album in the DB. This function is mapped to
// the path PUT /albums/{album_id}
func (v AlbumsResource) Update(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Album
  album := &models.Album{}

  if err := tx.Find(album, c.Param("album_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  // Bind Album to the html form elements
  if err := c.Bind(album); err != nil {
    return err
  }

  verrs, err := tx.ValidateAndUpdate(album)
  if err != nil {
    return err
  }

  if verrs.HasAny() {
    return responder.Wants("html", func (c buffalo.Context) error {
      // Make the errors available inside the html template
      c.Set("errors", verrs)

      // Render again the edit.html template that the user can
      // correct the input.
      c.Set("album", album)

      return c.Render(http.StatusUnprocessableEntity, r.HTML("/albums/edit.plush.html"))
    }).Wants("json", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
    }).Wants("xml", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
    }).Respond(c)
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // If there are no errors set a success message
    c.Flash().Add("success", T.Translate(c, "album.updated.success"))

    // and redirect to the show page
    return c.Redirect(http.StatusSeeOther, "/albums/%v", album.ID)
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.JSON(album))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.XML(album))
  }).Respond(c)
}

// Destroy deletes a Album from the DB. This function is mapped
// to the path DELETE /albums/{album_id}
func (v AlbumsResource) Destroy(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Album
  album := &models.Album{}

  // To find the Album the parameter album_id is used.
  if err := tx.Find(album, c.Param("album_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  if err := tx.Destroy(album); err != nil {
    return err
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // If there are no errors set a flash message
    c.Flash().Add("success", T.Translate(c, "album.destroyed.success"))

    // Redirect to the index page
    return c.Redirect(http.StatusSeeOther, "/albums")
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.JSON(album))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.XML(album))
  }).Respond(c)
}
