package actions

import (

  "fmt"
  "net/http"
  "github.com/gobuffalo/buffalo"
  "github.com/gobuffalo/pop/v5"
  "github.com/gobuffalo/x/responder"
  "jukedec_api/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Band)
// DB Table: Plural (bands)
// Resource: Plural (Bands)
// Path: Plural (/bands)
// View Template Folder: Plural (/templates/bands/)

// BandsResource is the resource for the Band model
type BandsResource struct{
  buffalo.Resource
}

// List gets all Bands. This function is mapped to the path
// GET /bands
func (v BandsResource) List(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  bands := &models.Bands{}

  // Paginate results. Params "page" and "per_page" control pagination.
  // Default values are "page=1" and "per_page=20".
  q := tx.PaginateFromParams(c.Params())

  // Retrieve all Bands from the DB
  if err := q.All(bands); err != nil {
    return err
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // Add the paginator to the context so it can be used in the template.
    c.Set("pagination", q.Paginator)

    c.Set("bands", bands)
    return c.Render(http.StatusOK, r.HTML("/bands/index.plush.html"))
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(200, r.JSON(bands))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(200, r.XML(bands))
  }).Respond(c)
}

// Show gets the data for one Band. This function is mapped to
// the path GET /bands/{band_id}
func (v BandsResource) Show(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Band
  band := &models.Band{}

  // To find the Band the parameter band_id is used.
  if err := tx.Find(band, c.Param("band_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    c.Set("band", band)

    return c.Render(http.StatusOK, r.HTML("/bands/show.plush.html"))
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(200, r.JSON(band))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(200, r.XML(band))
  }).Respond(c)
}

// New renders the form for creating a new Band.
// This function is mapped to the path GET /bands/new
func (v BandsResource) New(c buffalo.Context) error {
  c.Set("band", &models.Band{})

  return c.Render(http.StatusOK, r.HTML("/bands/new.plush.html"))
}
// Create adds a Band to the DB. This function is mapped to the
// path POST /bands
func (v BandsResource) Create(c buffalo.Context) error {
  // Allocate an empty Band
  band := &models.Band{}

  // Bind band to the html form elements
  if err := c.Bind(band); err != nil {
    return err
  }

  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Validate the data from the html form
  verrs, err := tx.ValidateAndCreate(band)
  if err != nil {
    return err
  }

  if verrs.HasAny() {
    return responder.Wants("html", func (c buffalo.Context) error {
      // Make the errors available inside the html template
      c.Set("errors", verrs)

      // Render again the new.html template that the user can
      // correct the input.
      c.Set("band", band)

      return c.Render(http.StatusUnprocessableEntity, r.HTML("/bands/new.plush.html"))
    }).Wants("json", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
    }).Wants("xml", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
    }).Respond(c)
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // If there are no errors set a success message
    c.Flash().Add("success", T.Translate(c, "band.created.success"))

    // and redirect to the show page
    return c.Redirect(http.StatusSeeOther, "/bands/%v", band.ID)
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(http.StatusCreated, r.JSON(band))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(http.StatusCreated, r.XML(band))
  }).Respond(c)
}

// Edit renders a edit form for a Band. This function is
// mapped to the path GET /bands/{band_id}/edit
func (v BandsResource) Edit(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Band
  band := &models.Band{}

  if err := tx.Find(band, c.Param("band_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  c.Set("band", band)
  return c.Render(http.StatusOK, r.HTML("/bands/edit.plush.html"))
}
// Update changes a Band in the DB. This function is mapped to
// the path PUT /bands/{band_id}
func (v BandsResource) Update(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Band
  band := &models.Band{}

  if err := tx.Find(band, c.Param("band_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  // Bind Band to the html form elements
  if err := c.Bind(band); err != nil {
    return err
  }

  verrs, err := tx.ValidateAndUpdate(band)
  if err != nil {
    return err
  }

  if verrs.HasAny() {
    return responder.Wants("html", func (c buffalo.Context) error {
      // Make the errors available inside the html template
      c.Set("errors", verrs)

      // Render again the edit.html template that the user can
      // correct the input.
      c.Set("band", band)

      return c.Render(http.StatusUnprocessableEntity, r.HTML("/bands/edit.plush.html"))
    }).Wants("json", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
    }).Wants("xml", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
    }).Respond(c)
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // If there are no errors set a success message
    c.Flash().Add("success", T.Translate(c, "band.updated.success"))

    // and redirect to the show page
    return c.Redirect(http.StatusSeeOther, "/bands/%v", band.ID)
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.JSON(band))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.XML(band))
  }).Respond(c)
}

// Destroy deletes a Band from the DB. This function is mapped
// to the path DELETE /bands/{band_id}
func (v BandsResource) Destroy(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Band
  band := &models.Band{}

  // To find the Band the parameter band_id is used.
  if err := tx.Find(band, c.Param("band_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  if err := tx.Destroy(band); err != nil {
    return err
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // If there are no errors set a flash message
    c.Flash().Add("success", T.Translate(c, "band.destroyed.success"))

    // Redirect to the index page
    return c.Redirect(http.StatusSeeOther, "/bands")
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.JSON(band))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.XML(band))
  }).Respond(c)
}
