package actions

import (

  "fmt"
  "net/http"
  "github.com/gobuffalo/buffalo"
  "github.com/gobuffalo/pop/v5"
  "github.com/gobuffalo/x/responder"
  "jukedec_api/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Song)
// DB Table: Plural (songs)
// Resource: Plural (Songs)
// Path: Plural (/songs)
// View Template Folder: Plural (/templates/songs/)

// SongsResource is the resource for the Song model
type SongsResource struct{
  buffalo.Resource
}

// List gets all Songs. This function is mapped to the path
// GET /songs
func (v SongsResource) List(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  songs := &models.Songs{}

  // Paginate results. Params "page" and "per_page" control pagination.
  // Default values are "page=1" and "per_page=20".
  q := tx.PaginateFromParams(c.Params())

  // Retrieve all Songs from the DB
  if err := q.All(songs); err != nil {
    return err
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // Add the paginator to the context so it can be used in the template.
    c.Set("pagination", q.Paginator)

    c.Set("songs", songs)
    return c.Render(http.StatusOK, r.HTML("/songs/index.plush.html"))
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(200, r.JSON(songs))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(200, r.XML(songs))
  }).Respond(c)
}

// Show gets the data for one Song. This function is mapped to
// the path GET /songs/{song_id}
func (v SongsResource) Show(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Song
  song := &models.Song{}

  // To find the Song the parameter song_id is used.
  if err := tx.Find(song, c.Param("song_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    c.Set("song", song)

    return c.Render(http.StatusOK, r.HTML("/songs/show.plush.html"))
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(200, r.JSON(song))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(200, r.XML(song))
  }).Respond(c)
}

// New renders the form for creating a new Song.
// This function is mapped to the path GET /songs/new
func (v SongsResource) New(c buffalo.Context) error {
  c.Set("song", &models.Song{})

  return c.Render(http.StatusOK, r.HTML("/songs/new.plush.html"))
}
// Create adds a Song to the DB. This function is mapped to the
// path POST /songs
func (v SongsResource) Create(c buffalo.Context) error {
  // Allocate an empty Song
  song := &models.Song{}

  // Bind song to the html form elements
  if err := c.Bind(song); err != nil {
    return err
  }

  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Validate the data from the html form
  verrs, err := tx.ValidateAndCreate(song)
  if err != nil {
    return err
  }

  if verrs.HasAny() {
    return responder.Wants("html", func (c buffalo.Context) error {
      // Make the errors available inside the html template
      c.Set("errors", verrs)

      // Render again the new.html template that the user can
      // correct the input.
      c.Set("song", song)

      return c.Render(http.StatusUnprocessableEntity, r.HTML("/songs/new.plush.html"))
    }).Wants("json", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
    }).Wants("xml", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
    }).Respond(c)
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // If there are no errors set a success message
    c.Flash().Add("success", T.Translate(c, "song.created.success"))

    // and redirect to the show page
    return c.Redirect(http.StatusSeeOther, "/songs/%v", song.ID)
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(http.StatusCreated, r.JSON(song))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(http.StatusCreated, r.XML(song))
  }).Respond(c)
}

// Edit renders a edit form for a Song. This function is
// mapped to the path GET /songs/{song_id}/edit
func (v SongsResource) Edit(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Song
  song := &models.Song{}

  if err := tx.Find(song, c.Param("song_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  c.Set("song", song)
  return c.Render(http.StatusOK, r.HTML("/songs/edit.plush.html"))
}
// Update changes a Song in the DB. This function is mapped to
// the path PUT /songs/{song_id}
func (v SongsResource) Update(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Song
  song := &models.Song{}

  if err := tx.Find(song, c.Param("song_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  // Bind Song to the html form elements
  if err := c.Bind(song); err != nil {
    return err
  }

  verrs, err := tx.ValidateAndUpdate(song)
  if err != nil {
    return err
  }

  if verrs.HasAny() {
    return responder.Wants("html", func (c buffalo.Context) error {
      // Make the errors available inside the html template
      c.Set("errors", verrs)

      // Render again the edit.html template that the user can
      // correct the input.
      c.Set("song", song)

      return c.Render(http.StatusUnprocessableEntity, r.HTML("/songs/edit.plush.html"))
    }).Wants("json", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
    }).Wants("xml", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
    }).Respond(c)
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // If there are no errors set a success message
    c.Flash().Add("success", T.Translate(c, "song.updated.success"))

    // and redirect to the show page
    return c.Redirect(http.StatusSeeOther, "/songs/%v", song.ID)
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.JSON(song))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.XML(song))
  }).Respond(c)
}

// Destroy deletes a Song from the DB. This function is mapped
// to the path DELETE /songs/{song_id}
func (v SongsResource) Destroy(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Song
  song := &models.Song{}

  // To find the Song the parameter song_id is used.
  if err := tx.Find(song, c.Param("song_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  if err := tx.Destroy(song); err != nil {
    return err
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // If there are no errors set a flash message
    c.Flash().Add("success", T.Translate(c, "song.destroyed.success"))

    // Redirect to the index page
    return c.Redirect(http.StatusSeeOther, "/songs")
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.JSON(song))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.XML(song))
  }).Respond(c)
}
